### ISSUE TITLE
the active tab not change position when pressed back button

### ISSUE THREAD

**Issue by Kelvin9393** [aurelhubert/ahbottomnavigation#123]
hello, I use bottom navigation to navigate between three fragments. If I am at first tab currently and I press third tab to navigate to third fragment, after that I press the back button. My fragment navigate back to first fragment successfully as I use addToBackStack(), but the active tab in bottom navigation still stay in third tab. Is there any method to solve this? I am new to Android programming and I am unfamiliar with it.

**Comment by aurelhubert** [comment]
Hello @Kelvin9393, I suggest you to not add the fragments to the back stack because it's not the expected behavior for the Android users. The bottom bar is here to show 3 to 5 different destinations to the user (for example, a news feed, a user profile, etc.). When you select a tab, you should just change the current fragment (and not create a fragments stack). The back button should only close the app, or re-open the previous screen if there is one (definitely not re-open the previous tab :) ). I suggest you to look at the demo sample, it's a simple implementation of the component which follows the Material Design guidelines (https://material.google.com/components/bottom-navigation.html).
