### ISSUE TITLE
Scroll bug new 

### ISSUE THREAD

**Issue by cowfighting** [aurelhubert/ahbottomnavigation#126]
Hi, please see the source code [scroll bug demo](https://github.com/cowfighting/BottomNavBugDemo).
The steps will appear bug:
`click Tab1 -> click Tab2 -> click Tab1(bug appear, Tab1's content cannot scroll.)`

**Comment by aurelhubert** [comment]
I've looked at your code, I think the problem comes from the tab host. I suggest you to use a ViewPager (like in the demo project). I don't have the time to check where exactly the problem is but you can if you want :) (I'm pretty sure it's not a problem with the lib but something related with the TabHost & fragments components).
