### ISSUE TITLE
Activity...

### ISSUE THREAD

**Issue by Heromine** [aurelhubert/ahbottomnavigation#14]
How should i use it with more activities?
For example 
`if (position == 1 && !wasSelected) {
                    i have to start a new activity here
                } `

How can i do it with in both the activities the bottom nav bar?
Should i start everytime a new activity and put a new bar with the setted item there?
Sorry but i am new at this...

**Comment by alan-rodriguez** [comment]
Use Fragments instead of Activities to accomplish this behavior. The demo includes an example of how to do this in [DemoActivity](https://github.com/aurelhubert/ahbottomnavigation/blob/cdb77f9da1067df89287fc9a5943ed3c464f01cf/demo/src/main/java/aurelhubert/com/ahbottomnavigation/DemoActivity.java#L52).

**Comment by Heromine** [comment]
You wrote 'for activity/fragment' ...

**Comment by aurelhubert** [comment]
@Heromine Yes, sorry for the misunderstood, when I say "Activity", it's more like you can put it in your activity and manage your content as you wish inside (with for example fragments).
