### ISSUE TITLE
Issues with NestedScrollView

### ISSUE THREAD

**Issue by FilipeOS** [aurelhubert/ahbottomnavigation#141]
Hi,

I've followed the READ ME file but I'm having issues.

I am not being able to place a NestedScrollView on my fragments.

Exercise 1: I've placed a NestedScrollView ONLY on my fragment, it works fine. But on the rest of the fragments don't (obvious).
Exercise 2: I've replaced my LinearLayout on my activity.xml for a NestedScrollView, content don't display on full screen....
Exercise 3: Normal LinearLayout (inside Coordinator), bottom Navigation overlaps the content (all fragments)

On all cases the Bottom Navigation overlaps the content (Except NestedScrollView).
I just need a decent solution to enable NestedScrollView on every fragments without overlap the content like it is now

![screenshot_20160822-165338](https://cloud.githubusercontent.com/assets/18313286/17861575/7ea1e0b6-6889-11e6-9f8e-a45659146d55.png)
...

Any help please? I spent hours on this.

**Comment by FilipeOS** [comment]
This support is so bad........... some one can help me?

**Comment by aurelhubert** [comment]
>This support is so bad...........

@FilipeOS First, please remember that I'm not here to do your own work, if you think I'm here to answer your question within 24 hours, go somewhere else.

That being said, if the problem is the overlap of the content, add some bottom padding or margin (yes, you can add padding on a Google Map object).

Good luck, and try to respect the community next time.
