### ISSUE TITLE
Draw a line on Top border

### ISSUE THREAD

**Issue by jesuisnicolasdavid** [aurelhubert/ahbottomnavigation#147]
i am looking to draw a line on the top border of the bottom bar but i am still struggling to implement it. I tried a background xml and a view inside AHBottomNavigation but nothing is working...

**Comment by aurelhubert** [comment]
The problem is that there is a LinearLayout drawn on top the the view container, so if you use `setBackground()`& `setBackgroundColor()`, you will not see anything. I suggest you to fork the project and apply a background directly on the LinearLayout (inside the method `createItems()` of the class `AHBottomNavigation`).

**Comment by jbarmanet** [comment]
You can use 9-patch image, with a top border that won't scale vertically, name it say "tabbar_bg.9.png" and import it into your drawables. Then do: 
`yourNavigationBottomBar.setDefaultBackgroundResource(R.drawable.tabbar_bg)` 
and you're set!
