### ISSUE TITLE
ViewPager Loads All Pages

### ISSUE THREAD

**Issue by nsuthar20** [aurelhubert/ahbottomnavigation#215]
I have a problem with five fragments with `ahbottomnavigation`. It loads all pages when application started.
 I also tries to set: `mViewPager.setOffScreenPageLimit(0);` , it works, but it reloads each visible page when i tried to change position. I think it's a problem with `ViewPager`, but i need to solve it out. any Suggetion?

**Comment by aurelhubert** [comment]
You're right, the problem comes from how the view pager manages its elements. I suggest you to keep your initial value for `setOffScreenPageLimit`. The second step is to add a method in each fragment to load the content when you display them, and call this method when the user click on a tab (be sure to load the content of a fragment only once to avoid unnecessary work).

**Comment by nsuthar20** [comment]
```
private boolean _hasLoadedOnce = false; // your boolean field

    @Override
    public void setUserVisibleHint(boolean isVisibleToUser) {
        super.setUserVisibleHint(isVisibleToUser);

        if (this.isVisible()) {
            // we check that the fragment is becoming visible
            if (this.isVisible() && !_hasLoadedOnce) {
               //code
            }
        }
    }
```
worked with this code!
