### ISSUE TITLE
How to set default item in onCreate()

### ISSUE THREAD

**Issue by TonySoprano003** [aurelhubert/ahbottomnavigation#260]
How to set default item in onCreate()?
I use setCurrentItem(2) occur Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.dc.oa.fragments.HomeFragment.willBeDisplayed()' on a null object reference

**Comment by aurelhubert** [comment]
The problem here is that you set the current item before creating your fragment(s). If you have added a listener to your AHBottomNavigation (with `setOnTabSelectedListener`), it will be called directly (and maybe too soon). Be careful in your implementation (you can simply add a null test before calling `willBeDisplayed()`).
