### ISSUE TITLE
View weight

### ISSUE THREAD

**Issue by Onregs** [aurelhubert/ahbottomnavigation#271]
Hello, Is there an option to change the weight of views to 1? So with it will be comfortable to change the visibility (to GONE) of unnecessary items.

**Comment by aurelhubert** [comment]
I'm not sure to understand, which view(s) exactly?

**Comment by Onregs** [comment]
I mean views which placed in the bottom navigation. So for example width of bottom navigation is 100dp and I have 5 views, so each view gets 20dp. If we set a visibility one of view to GONE (now 4 visible) that views won't have 25dp width. I checked AHBottomNavigation.class so navigation uses LinearLayout container and will be great to have an opportunity to change the weight of navigation views.

**Comment by aurelhubert** [comment]
Okay, I understand. The problem here is that the tabs have a minimum and maximum widths (which can be found here: https://material.io/guidelines/components/bottom-navigation.html). If you set a width to the bottom navigation, it will probably break some UI elements. You can try to fork the library and test your idea to check if it shows the expected behavior.
