### ISSUE TITLE
About the Auto Hide of Bottom Bar while scrolling the recycling view

### ISSUE THREAD

**Issue by hilarycheng** [aurelhubert/ahbottomnavigation#37]
It seems you got a demo gif about this features. But I cannot find related demo code for this feature. Would you mind tell us the api ?

**Comment by aurelhubert** [comment]
@hilarycheng You can found an example in the demo, when selecting the second or third tab.

To use it, you have to place your content inside a CoordinatorLayout:

```xml
<android.support.design.widget.CoordinatorLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <FrameLayout
        android:id="@+id/fragment_container"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>

    <com.aurelhubert.ahbottomnavigation.AHBottomNavigation
        android:id="@+id/bottom_navigation"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom" />

</android.support.design.widget.CoordinatorLayout>
```

Put your RecyclerView inside the FrameLayout (in the XML or with a fragment transaction).

**Comment by CCorrado** [comment]
I am doing this, with a Fragment being added to the Frame layout, and still the navigation bar does not collapse/expand as expected when scrolling the recycler view. Is it because the Fragment itself is also a Coordinator Layout? So, I have what you've written above, and the Fragment is a Coordinator Layout wrapping a AppbarLayout + FAB + RecyclerView. Looks like this doesn't work.
