### ISSUE TITLE
Auto hide bottom navigation when softkeyboard appears.

### ISSUE THREAD

**Issue by septemberboy7** [aurelhubert/ahbottomnavigation#63]
I'm having to detect soft keyboard to show/hide the bottom navigation. Please add that feature.

**Comment by aurelhubert** [comment]
@septemberboy7 It's a bit complicated on Android because there are no methods like on iOS to detect when the keyboard is opening or closing. I suggest you to manage that in your code with these methods (and maybe update the windowSoftInputMode for your activity in your Manifest):

`hideBottomNavigation(boolean withAnimation)`
`restoreBottomNavigation(boolean withAnimation)`
