### ISSUE TITLE
Support for item with custom layout

### ISSUE THREAD

**Issue by matthew2402** [aurelhubert/ahbottomnavigation#88]
I know it's against the material design guidelines but a support for setting a menu item with a custom layout would be nice.
For example I want to add a profile image in the end of the bar.
Thanks in advance ;)

**Comment by aurelhubert** [comment]
@matthew2402 I suggest you to fork the library. The problem here (apart from following the Material Design guidelines) is that every tab contains an image, a textview for the title and a textview for the notification. Every view is animated and moves when the user interacts with the bottom navigation. If I add custom layout, there will be a lot more cases to manage.

For now, I prefer keep the library as clean as possible and avoid custom implementations, but feel free to do it ;)
