### ISSUE TITLE
can I add item more than 5?like iOS navigatorController last item is "more" label

### ISSUE THREAD

**Issue by linjson** [aurelhubert/ahbottomnavigation#95]

**Comment by aurelhubert** [comment]
For now, no, because this library follows the guidelines of Material Design (which recommends 3 to 5 tabs). If you have more than 5 items, I suggest you to use:
- Tabs (https://www.google.com/design/spec/components/tabs.html)
- Navigation Drawer (https://www.google.com/design/spec/patterns/navigation-drawer.html)
